jennie/jennie/urls.py
from django.contrib import admin
from django.urls import path, include
from products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.list, name="list"),
    path('really/', include('really.urls')),
    path('products/', include('products.urls')),
]

jennie/products/urls.py
from django.urls import path
from. import views

app_name = "products"
urlpatterns = [
    path('create/', views.create, name='create'),
    path('show/<int:id>/', views.show, name='show'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

jennie/really/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('first/', views.first, name="first"),
    path('second/', views.second, name="second" ),
    path('third/', views.third, name="third"),
]

jennie/products/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=200)
    description= models.TextField()
    price= models.IntegerField(null=True)
    view_count = models.IntegerField(blank=True, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
# Create your models here.

jennie/really/models.py
from django.db import models

# Create your models here.

jennie/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models  import Product
import pdb


def list(request):
    products = Product.objects.all()
    return render(request, 'list.html', {'all_products':products})

def create(request):
    if request.method == "POST":
        title= request.POST.get('title')
        description = request.POST.get('description')
        price = request.POST.get('price')
        product=Product.objects.create(title=title, price=price, description=description) 
        product.save() 
        return redirect('list')
        
    return render(request, 'create.html')
    


def show(request, id):
    product = get_object_or_404(Product, pk=id)
    default_view_count = product.view_count
    product.view_count = default_view_count + 1    
    return render(request, 'show.html', {'product':product})
    
def edit(request, id):
    product = get_object_or_404(Product, pk=id)
    return render(request, 'edit.html', {'product': product})
    

def update(request, id):
    if request.method == "POST":
        product = Product.objects.get(pk=id)
        title = request.POST.get('title')
        description = request.POST.get('description')
        price = int(request.POST.get('price'))
        product.title = title
        product.description = description
        product.price = price
        product.save()
    return redirect('products:show', product.pk)
    

def delete(request, id):
    if request.method == "POST":
        product= Product.objects.get(pk=id)
        product.delete()
    return redirect('list')
# Create your views here.

jennie/really/views.py
from django.shortcuts import render

def first(request):
    return render(request, 'first.html')
    
    
def second(request):
    return render(request, 'second.html')
    
    
def third(request):
    return render(request, 'third.html')
# Create your views here.

jennie/products/templates/create.html
{% extends 'base.html' %}

{% block content %}


<center><img src="{% static 'image/g.PNG' %}"></img></center>


<br><br><br><center><img src="{% static 'image/gg.PNG' %}" alt="" class="n"></img></center><br><br>

<center><img src="{% static 'image/g.PNG' %}"></img></center>




<form action="{% url 'products:create' %}" method="POST">
    {% csrf_token %}
    <center><label><img src="{% static 'image/a.PNG' %}"></img></label></center>
   <center> <input type="text" name="title"></center><br><br>
    
    <center><label for="price"><img src="{% static 'image/b.PNG' %}"></img></label></center>
    <center><input type="number" name="price"></center><br><br>
    <center><label><img src="{% static 'image/c.PNG' %}"></label></center>
    <center><textarea name="description"></textarea></center><br><br>
    
    <center><input type="submit" class="btn btn-primary" value="등록"></center>
    
</form>
{% endblock %}

jennie/products/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<h1> 상품정보 수정하기</h1>

<form action="{% url 'products:update' product.pk %}" method="POST">
    {% csrf_token %}
    <label>상품이름</label><br>
    <input type="text" name="title" value="{{ product.title }}" ><br><br>
    
    <label>상품가격</label><br><br>
    <input type="number" name="price"><br><br>
    <labe>설명</labe>
    <textarea name="description">{{ product.description }}</textarea><br><br>
    
    <input type="submit" class="btn btn-primary" value="수정">
    
</form>

{% endblock %}

jennie/products/templates/list.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
  
  <center><img src="{% static 'image/o.PNG' %}"></img></center>

<center><img src="{% static 'image/q.gif' %}"></img></center>

  <center><img src="{% static 'image/o.PNG' %}"></img></center>
  <center><img src="{% static 'image/r.PNG' %}"></img></center>

   
 
 {% for item in all_products %} 
 <center><div class="card col-4" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ item.title }}</h5>
    <p class="card-text">{{ item.description }}</p>
    <a href="{% url 'products:show' item.id %}" class="btn btn-primary">Go</a>
    
  </div>
</div></center>
{% endfor %}
{% endblock %}

jennie/products/templates/show.html
{% extends 'base.html' %}

{% block content %}
  <h1> 상품 상세보기 페이지 입니다.</h1>
  
  <h2>상품이름 : {{ product.title }}</h2>
  <h3>상품가격: {{ product.price }}</h3>
  <p>상품 설명 : {{ product.description }}</p>
  
  <a href="{% url 'products:edit' product.pk %}  " class="btn btn-primary">수정</a>
  <a href="#" class="btn btn-primary" date-toggle="modal" date-target="#exampleModal">삭제</a>
 

 <!-- Modal -->
 <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
      </div>
   </div>
 </div>


{% endblock %}

jennie/really/templates/first.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<center><img src="{% static 'image/je.gif' %}" alt="" class="n"></img></center><br><br>

<center><a href="{% url 'products:create' %}"><img src="{% static 'image/click.GIF' %}"></a></center>

{% endblock %}

jennie/really/templates/second.html
{% extends 'base.html' %}

{% block content %}
<h2>two</h2>
<a href="{% url 'third' %}">Three로 가자</a>
{% endblock %}

jennie/really/templates/third.html
{% extends 'base.html' %}

{% block content %}
<h3>asdfasdfaewqr</h3>
{% endblock %}

jennie/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <title>blackpink</title>
  </head>
  <body>
      <div class="container">
     
    {% block content %}
    
    {% endblock %}
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>